### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.tess4j.TessAPI

### ISSUE THREAD

**Issue by shlok-pardeshi** [tesseract-ocr/tesseract#3204]
### Environment

* **Tesseract Version**:  4.5.4
* **Commit Number**: 
* **Platform**: Mcbook Big Sur Version 11.1

### Current Behavior:
Exception in thread "Thread-104" java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.tess4j.TessAPI
	at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:426)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:310)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:293)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:274)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:258)
	at com.shivshahi.shivshahi.TesseractReadTextFromImageAndReturn.tesseractReadTextMarathi(TesseractReadTextFromImageAndReturn.java:59)
	at com.shivshahi.shivshahi.voter1to30thread.ThreadHeader.getTextFromImagesForHeade(ThreadHeader.java:75)
	at com.shivshahi.shivshahi.voter1to30thread.ThreadHeader.callRun(ThreadHeader.java:63)
	at com.shivshahi.shivshahi.voter1to30thread.ThreadHeader.run(ThreadHeader.java:42)

### Suggested Fix:

This Code is working fine on windows 7 but not working on MacBook Big Sur 11.1

Part of code:-

Tesseract tesseract = new Tesseract();
tesseract.setDatapath("tessdata");
tesseract.setDatapath(dataPath);
tesseract.setTessVariable("user_defined_dpi", "300");
tesseract.setLanguage("eng");
return tesseract.doOCR(bufferedImage);

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. reproduce your problem with resent version of tesseract executable  or C++/C.
