### ISSUE TITLE
RFC: Supported Compilers, C++17

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#3210]
From the README.md:

>Supported Compilers are:
>
>* GCC 4.8 and above
>* Clang 3.4 and above
>* MSVC 2015, 2017, 2019
>
>Other compilers might work, but are not officially supported.

Can we update this to:

>Supported Compilers are:
>
>* GCC 8.1 and above
>* Clang 7 and above
>* MSVC 2019, 2017 15.8
>
>Other compilers might work, but are not officially supported.

Also, the options to compile to C++11 and C++14 will be removed.

**Comment by amitdo** [comment]
@zdenop,

Do you agree with these changes?

**Comment by stweil** [comment]
Did someone check that the current code really requires C++17?

**Comment by egorpugin** [comment]
I did not push really C++17. Probably I used couple of features from it by mistake. They can easily be rewritten in 11/14 to make tess5 release pre-C++17.

**Comment by egorpugin** [comment]
It would be better if we release 5.0.0 with pre C++17 and then in master 6.0.0 branch we can fully use C++17.
We can also use C++17 in training tools (and tests) since they are for the "expert" usage.

**Comment by amitdo** [comment]
>Did someone check that the current code really requires C++17?

I didn't.

Did someone test that old compiler that does not support C++ 17 (or have only partial support) can compile the latest codebase?

There is a [report](https://github.com/tesseract-ocr/tesseract/issues/2618) that GCC 4.8 fails to compile 5.0.

What about 4.9, 5.x ?

GCC 8 is supported by these LTS Linux distros:
Debian 10, Ubuntu 18.04 & 20.04 (16.04 has an official GCC PPA), RHEL/CentOS 7 & 8, SLES 12 & 15, openSUSE 15.2.

Clang 7 is supported by these LTS Linux distros:
Debian 9 & 10, Ubuntu 18.04 & 20.04, RHEL/CentOS 7 & 8, SLES 15, openSUSE 15.2.

**Comment by egorpugin** [comment]
I think we do not need to bother about listing everything.
Modern way is to delcare C++11/14/17/20.
User will choose appropriate compiler himself.

**Comment by amitdo** [comment]
Compilers 'declare' that they support  a C++ standard before they have official (non-experimental) full support for that standard.

Also, the library support in compilers is lagging the language support.

**Comment by egorpugin** [comment]
1. Check this page for compiler support https://en.cppreference.com/w/cpp/compiler_support
2. We do not need to care about compilers, language support, stdlib. C++17 is supported in main three compilers today.

**Comment by zdenop** [comment]
IMO if you work on servers or linux distribution it is almost impossible for user to choose compiler - you have to use what is supported by default installation. 

From 4.0  [tesseract needs c++11 support](https://github.com/tesseract-ocr/tesseract/blob/4.0/configure.ac#L350), so I would suggest c++14 for 5.0.

If I understand correctly e.g. current [LTS Debian](https://wiki.debian.org/LTS) Stretch [has available g++6](https://packages.debian.org/stretch/g++) for this c++14 should not be problem. 
Maybe @AlexanderP as tesseract packager for several distros can give some insight.

**Comment by amitdo** [comment]
Debian 10 'Buster' is the latest stable release.

https://www.debian.org/releases/buster/

https://packages.debian.org/buster/g++

Debian 'Stretch; is 'oldstable'.

https://www.debian.org/releases/stretch/

it is not supported by the Debian project anymore, but it is supported by a third party organization.

**Comment by egorpugin** [comment]
> IMO if you work on servers or linux distribution it is almost impossible for user to choose compiler 

We can't stop doing improvements looking at them or at any distro.
We depend only on compilers/standard.

**Comment by amitdo** [comment]
Also, as I said 9 Stretch has an alternative C++17 compiler.

https://packages.debian.org/buster/clang

**Comment by amitdo** [comment]
IMO, we need to support something in between 'latest and greatest' and 'too old' versions of compilers.

**Comment by egorpugin** [comment]
That's why for 5.0.0 we use preC++17, and for 6.0.0 it is C++17. (It is 3 full years from 2017 already.)

**Comment by mdecerbo** [comment]
I can confirm that on CentOS 7.6.1810, today's tip of Tesseract master fails to compile with the latest gcc package, `4.8.5-44.el7`.
The very long C++ error message begins with
```
  CXX      src/api/libtesseract_la-baseapi.lo
In file included from ./src/dict/dawg.h:32:0,
                 from ./src/dict/dawg_cache.h:23,
                 from src/api/baseapi.cpp:31:
./src/ccutil/params.h: In constructor 'tesseract::StringParam::StringParam(const char*, const char*, const char*, bool, tesseract::ParamsVectors*)':
./src/ccutil/params.h:208:34: error: no matching function for call to 'tesseract::STRING::STRING()'
       : Param(name, comment, init) {
```

After installing `devtoolset-7` on the same machine (`yum install centos-release-scl ; yum install devtoolset-7-gcc*`) tesseract builds fine with `devtoolset-7-gcc-c++-7.3.1-5.16.el7.x86_64`.

**Comment by amitdo** [comment]
http://mirror.centos.org/centos/7/sclo/x86_64/rh/Packages/d/

devtoolset-x

Version 7, 8 and 9 are available.

**Comment by amitdo** [comment]
G++ 6 fails to compile commit e3fd938bca0e.

#3255

**Comment by egorpugin** [comment]
Exactly that's why we must move to C++17 in tess6.0.0.
Not using modern C++ is not productive.

**Comment by stweil** [comment]
>  Not using modern C++ is not productive.

Support for old C++-11 compilers like gcc-6 only requires small modifications for the `STRING` class and a replacement for the current use of `emplace_back`, so maybe that's worth the effort.

**Comment by amitdo** [comment]
Clang 7.0 is also available for Debian Stretch. It also fails to compile the current 5.0 code, in both C++17 and C++14 mode, with libc++ 7 or libstdc++ 6.

**Comment by amitdo** [comment]
GCC 7 - compilation works in C++17.
Does not work in C++14 mode.

So the current status of the 5.0 code is:

Can be compiled in **C++17 only**.

Supported Compilers:
* GCC >= 7
* Clang >= 7 (10, 11 pass tests in CI, 9 does not)
* MSVC 2019

**Comment by egorpugin** [comment]
fyi: https://google.github.io/styleguide/cppguide.html#C++_Version

> Currently, code should target C++17, i.e., should not use C++2x features. The C++ version targeted by this guide will advance (aggressively) over time.

**Comment by egorpugin** [comment]
Ok, tess5.0 will be C++17.
See https://github.com/tesseract-ocr/tesseract/commit/0f1296c6f623f2070118e125bf5a1b8662afb4d9#r48016802

Please send PRs (or update if you have rights) with build/doc/readme/tessdoc repo/other changes.
Remove any compilers from any requirements.
The only requirement is C++17.
Therefore users just must use compilers with C++17 support. It is doable today.
