### ISSUE TITLE
3.05 branch build failure

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#1000]
* **Tesseract Version**: 3.05.01 
* **Commit Number**: latest code from 3.05 branch
* **Platform**: ubuntu 14.04

### Current Behavior:

First reported on forum - https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/g8lTxxYiJ2E/KL07qF_LAQAJ

Build is failing with the following:

```
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11  -L/usr/local/lib -o tesseract tesseract-tesseractmain.o libtesseract.la  -lrt -lpthread
libtool: link: g++ -g -O2 -std=c++11 -o .libs/tesseract tesseract-tesseractmain.o  -L/usr/local/lib ./.libs/libtesseract.so -lrt -lpthread
/usr/bin/ld: tesseract-tesseractmain.o: undefined reference to symbol 'lept_free'
//usr/local/lib/liblept.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [tesseract] Error 1
make[2]: Leaving directory `/home/sanskrit/tesseract-3.05/api'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/sanskrit/tesseract-3.05'
make: *** [all] Error 2
```

This is using the latest code from github for leptonica as well as tesseract 3.05 branch.

Build was done using following commands:

```
git clone -q --branch=3.05 https://github.com/tesseract-ocr/tesseract.git tesseract-3.05
cd tesseract-3.05
./autogen.sh
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig 
LIBLEPT_HEADERSDIR=/usr/local/include
./configure --with-extra-includes=/usr/local/include --with-extra-libraries=/usr/local/lib
make
```

**Comment by stweil** [comment]
I don't think this is related to Tesseract. The same sequence works for me on Debian Jessie and Stretch. Maybe a damaged local Leptonica build or installation?

**Comment by Shreeshrii** [comment]
Same leptonica works for tesseract master branch

```
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11  -L/usr/local/lib -o tesseract tesseract-tesseractmain.o libtesseract.la -L/usr/local/lib -llept   -fopenmp  -lrt -lpthread
libtool: link: g++ -g -O2 -std=c++11 -o .libs/tesseract tesseract-tesseractmain.o -fopenmp  -L/usr/local/lib ./.libs/libtesseract.so /usr/local/lib/liblept.so -lrt -lpthread -fopenmp
make[2]: Leaving directory `/home/sanskrit/tesseract/api'
Making all in .
make[2]: Entering directory `/home/sanskrit/tesseract'
make[2]: Leaving directory `/home/sanskrit/tesseract'
Making all in tessdata
make[2]: Entering directory `/home/sanskrit/tesseract/tessdata'
Making all in configs
make[3]: Entering directory `/home/sanskrit/tesseract/tessdata/configs'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/sanskrit/tesseract/tessdata/configs'
Making all in tessconfigs
make[3]: Entering directory `/home/sanskrit/tesseract/tessdata/tessconfigs'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/sanskrit/tesseract/tessdata/tessconfigs'
make[3]: Entering directory `/home/sanskrit/tesseract/tessdata'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/home/sanskrit/tesseract/tessdata'
make[2]: Leaving directory `/home/sanskrit/tesseract/tessdata'
Making all in doc
make[2]: Entering directory `/home/sanskrit/tesseract/doc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/sanskrit/tesseract/doc'
make[1]: Leaving directory `/home/sanskrit/tesseract'
```

**Comment by Shreeshrii** [comment]
I notice some differences in the libtool commands for 3.05  and 4.0

3.05
```
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11  \
-L/usr/local/lib -o tesseract tesseract-tesseractmain.o libtesseract.la  \
-lrt -lpthread

libtool: link: g++ -g -O2 -std=c++11 -o .libs/tesseract tesseract-tesseractmain.o  \
-L/usr/local/lib ./.libs/libtesseract.so \
-lrt -lpthread
```

4.0
```
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11  \
-L/usr/local/lib -o tesseract tesseract-tesseractmain.o libtesseract.la \
-L/usr/local/lib -llept   -fopenmp  \
-lrt -lpthread

libtool: link: g++ -g -O2 -std=c++11 -o .libs/tesseract tesseract-tesseractmain.o -fopenmp \
-L/usr/local/lib ./.libs/libtesseract.so \
 /usr/local/lib/liblept.so \
-lrt -lpthread -fopenmp
```

**Comment by stweil** [comment]
So 3.05 tries linking without the Leptonica library. That cannot work of course.

You used `LIBLEPT_HEADERSDIR`. I did not find it in the code, so I think that is without any effect. The other options for `configure`, namely `--with-extra-includes` and `--with-extra-libraries` should not be needed. Setting `PKG_CONFIG_PATH` should be sufficient if you have installed code in `/usr/local`. I try to avoid such extra settings because they are confusing: which installation of Leptonica is used? Therefore I usually install in `/usr` (see my packages at https://digi.bib.uni-mannheim.de/tesseract/leptonica/).

**Comment by Shreeshrii** [comment]
I was following the instructions from the compiling page. I will try again just with PKG_CONFIG_PATH.

**Comment by Shreeshrii** [comment]
I have tried multiple times, different options, still getting same error.

Do not know whether it is because I am using the latest version of leptonica rather than 1.74.2.

@danbloomberg Has anything changed between 1.74.2 to latest code to cause this breakage?

**Comment by DanBloomberg** [comment]
I don't know what the breakage is.  In this thread I see the failure to load liblept in 3.05, which might have followed from the failure to find lept_free() for some reason.

@shreeshrii  you say it works for the master branch; for what version does it fail, and what is the failure?

**Comment by Shreeshrii** [comment]
Dan, 

I had built leptonica with latest ocde from github (after even 1.74.4). I was able to build master branch of tesseract with it. However, when I tried building the 3.05 branch it failed with the error related to lept_free().

I now rebuilt leptonica 1.74.2 ( git reset --hard 395728da046016859864eeb99c7a48121acaeb74) and am able to build tesseract 3.05.

```
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -std=c++11   -o tesseract tesseract-tesseractmain.o libtesseract.la  -lrt -lpthread
libtool: link: g++ -g -std=c++11 -o tesseract tesseract-tesseractmain.o  ./.libs/libtesseract.a -L/usr/local/lib /usr/local/lib/liblept.so -lz -lpng12 -ljpeg -lgif /usr/lib/x86_64-linux-gnu/libtiff.so -lwebp -lopenjp2 -lrt -lpthread

make[2]: Leaving directory `/home/sanskrit/tesseract-3.05/api'
Making all in .
make[2]: Entering directory `/home/sanskrit/tesseract-3.05'
make[2]: Leaving directory `/home/sanskrit/tesseract-3.05'
Making all in tessdata
```

**Comment by Shreeshrii** [comment]
Another possibility is that the configure process is checking specifically for 1.74.2 ?

**Comment by stweil** [comment]
@Shreeshrii , please try these four commands:

    pkg-config --cflags lept
    pkg-config --libs lept
    PKG_CONFIG_PATH=/usr/local/lib/pkgconfig pkg-config --cflags lept
    PKG_CONFIG_PATH=/usr/local/lib/pkgconfig pkg-config --libs lept

Here is my output (only two commands, as I have no installation in `/usr/local`):

    $ pkg-config --cflags lept
    -I/usr/include/leptonica
    $ pkg-config --libs lept
    -llept

Your build output neither shows something like `-I/usr/local/include/leptonica` (for the C++ compiler) nor `-L/usr/local/lib -llept`, so I expect that you have a broken file `lept.pc` somewhere on your computer. The above test will check that.

**Comment by Shreeshrii** [comment]
```
$ pkg-config --cflags lept
-I/usr/local/include/leptonica
$ pkg-config --libs lept
-L/usr/local/lib -llept
$ PKG_CONFIG_PATH=/usr/local/lib/pkgconfig pkg-config --cflags lept
-I/usr/local/include/leptonica
$ PKG_CONFIG_PATH=/usr/local/lib/pkgconfig pkg-config --libs lept
-L/usr/local/lib -llept
```

**Comment by DanBloomberg** [comment]
lept.pc.in  is from Jan 2016, and lept.pc.cmake is from Apr 22, 2017.

Neither have changed since 1.74.2, which was May 19, 2017.

**Comment by Shreeshrii** [comment]
Here is config.log from the build with 1.74.4 - which had the error.

[config.log.txt](https://github.com/tesseract-ocr/tesseract/files/1089334/config.log.txt)

**Comment by DanBloomberg** [comment]
My 1.74.4 builds fine with autotools on linux.

I don't have a conftest.cpp file, and configure doesn't look for it.
Attaching my lept.pc (generated from lept.pc.in).
[lept.pc.txt](https://github.com/tesseract-ocr/tesseract/files/1089399/lept.pc.txt)

**Comment by stweil** [comment]
@Shreeshrii, does the build work with my [3.05](https://github.com/stweil/tesseract/tree/3.05) (I just added a [backported commit](https://github.com/stweil/tesseract/commit/e7610d86c97de4c29777892465fc4c3bc77e8da8))?

**Comment by Shreeshrii** [comment]
Dan, Leptonica is building fine. The problem is in building tesseract 3.05 branch.

Stefan, I will try building with your 3.05 and report.

Thank you both for your prompt responses.

**Comment by Shreeshrii** [comment]
@stweil Tesseract part of the build happened correctly using your 3.05. 

I am now getting similar error with `make training`.

```
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11   -o text2image text2image.o libtesseract_training.la libtesseract_tessopt.la -licui18n -licuuc -licudata   -licuuc -licudata    ../api/libtesseract.la -licuuc -licudata   -lpango-1.0 -lpangocairo-1.0 -lgobject-2.0 -lglib-2.0 -lcairo -lpangoft2-1.0 -lfontconfig  -lpthread
libtool: link: g++ -g -O2 -std=c++11 -o .libs/text2image text2image.o  ./.libs/libtesseract_training.a ./.libs/libtesseract_tessopt.a -licui18n ../api/.libs/libtesseract.so -licuuc -licudata -lpango-1.0 -lpangocairo-1.0 -lgobject-2.0 -lglib-2.0 /usr/lib/x86_64-linux-gnu/libcairo.so -lpangoft2-1.0 -lfontconfig -lpthread
/usr/bin/ld: text2image.o: undefined reference to symbol 'pixGetHeight'
//usr/local/lib/liblept.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [text2image] Error 1
make[1]: Leaving directory `/home/sanskrit/tesseract-3.05/training'
make: *** [training] Error 2
make[1]: Entering directory `/home/sanskrit/tesseract-3.05/training'
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11   -o text2image text2image.o libtesseract_training.la libtesseract_tessopt.la -licui18n -licuuc -licudata   -licuuc -licudata    ../api/libtesseract.la -licuuc -licudata   -lpango-1.0 -lpangocairo-1.0 -lgobject-2.0 -lglib-2.0 -lcairo -lpangoft2-1.0 -lfontconfig  -lpthread
libtool: link: g++ -g -O2 -std=c++11 -o .libs/text2image text2image.o  ./.libs/libtesseract_training.a ./.libs/libtesseract_tessopt.a -licui18n ../api/.libs/libtesseract.so -licuuc -licudata -lpango-1.0 -lpangocairo-1.0 -lgobject-2.0 -lglib-2.0 /usr/lib/x86_64-linux-gnu/libcairo.so -lpangoft2-1.0 -lfontconfig -lpthread
/usr/bin/ld: text2image.o: undefined reference to symbol 'pixGetHeight'
//usr/local/lib/liblept.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [text2image] Error 1
make[1]: Leaving directory `/home/sanskrit/tesseract-3.05/training'
make: *** [training-install] Error 2
```

**Comment by stweil** [comment]
Sorry, the fix for `training/Makefile.am` was missing. Updated now.

**Comment by Shreeshrii** [comment]
Thank you, @stweil. It was able to build 3.05 branch with the latest leptonica.

```
~$ tesseract -v
tesseract 3.05.01
 leptonica-1.74.2
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.4.0 : libopenjp2 2.1.2
```

However, even though I have built the latest leptonica (1.74.4), version info is still reporting 1.74.2. So, you maybe right that there maybe some old  file somewhere ...

Is there a way to check the version info for leptonica, other than through `tesseract -v`?

**Comment by amitdo** [comment]
Try this:
`find /usr -name *lept*`

**Comment by amitdo** [comment]
You need to recompile Tesseract after you re-installed Leptonica

**Comment by stweil** [comment]
... or use `ldd /usr/local/bin/tesseract` to see which libraries are used. Maybe `LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/tesseract -v` gets the expected Leptonica version.

**Comment by stweil** [comment]
> You need to recompile Tesseract after you re-installed Leptonica

In most cases this is not necessary, because typically Leptonica is not linked statically. That means Tesseract uses a shared library for Leptonica, and that library can be replaced by a newer one without harm (as long as there are no incompatible changes).

**Comment by amitdo** [comment]
>... (as long as there are no incompatible changes).

https://github.com/DanBloomberg/leptonica/issues/240

**Comment by Shreeshrii** [comment]
```
$ find /usr -name *lept*
/usr/share/doc/liblept4
/usr/share/doc/liblept5
/usr/lib/liblept.so.4.0.2
/usr/lib/liblept.so.4
/usr/lib/x86_64-linux-gnu/liblept.so.5.0.1
/usr/lib/x86_64-linux-gnu/liblept.so.5
/usr/local/include/leptonica
/usr/local/include/leptonica/leptwin.h
/usr/local/lib/liblept.so.5.0.1
/usr/local/lib/liblept.so.5
/usr/local/lib/liblept.la
/usr/local/lib/pkgconfig/lept.pc
/usr/local/lib/liblept.a
/usr/local/lib/liblept.so

$  ldd /usr/local/bin/tesseract
        linux-vdso.so.1 =>  (0x00007ffe1c126000)
        liblept.so.5 => /usr/local/lib/liblept.so.5 (0x00007f2d0d207000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2d0cfe9000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2d0cce4000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2d0c9de000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2d0c7c8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2d0c3ff000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2d0c1e6000)
        libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f2d0bfc0000)
        libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f2d0bd6a000)
        libgif.so.4 => /usr/lib/x86_64-linux-gnu/libgif.so.4 (0x00007f2d0bb61000)
        libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f2d0b8ef000)
        libwebp.so.5 => /usr/lib/x86_64-linux-gnu/libwebp.so.5 (0x00007f2d0b696000)
        libopenjp2.so.7 => /usr/lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007f2d0b45b000)
        /lib64/ld-linux-x86-64.so.2 (0x000055d6a8161000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f2d0b238000)
        libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f2d0b02a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2d0ae26000)

$ LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/tesseract -v
tesseract 4.00.00dev-549-g2b854e3
 leptonica-1.74.2
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.4.0 : libopenjp2 2.1.2

```

**Comment by stweil** [comment]
So it's using the Leptonica from `/usr/local` which claims to be leptonica-1.74.2.

**Comment by Shreeshrii** [comment]
But I built using latest leptonica sources, config.log as well as allheaders.h have patch level as 4.

I will rebuild again and see. 

Thanks!

**Comment by Shreeshrii** [comment]
I built leptonica again after doing `make distclean` , now I get the correct lib version. Thanks!

```
tesseract -v
tesseract 4.00.00dev-549-g2b854e3
 leptonica-1.74.4
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.4.0 : libopenjp2 2.1.2

```

**Comment by DanBloomberg** [comment]
@shreeshrii  Is it worth doing a mini-postmortem on this?  Just a couple of paragraphs on what went wrong and what we might do to prevent this from happening again.

**Comment by Shreeshrii** [comment]
@DanBloomberg 

I usually update leptonica by using the following script in the leptonica directory.

```
#!/bin/bash
git pull origin
./autobuild
./configure --disable-dependency-tracking 
#./configure
make
sudo make install
sudo ldconfig
```
I follow a similar build script for tesseract master branch for building 4.0. 

Based on an error report in the forum, I tried building 3.05.01 and received the error related to lept_free (reported above).

As part of the experimentation, I did a hard reset in leptonica directory at one time to get to the commit for 1.74.2 and built leptonica and tesseract 3.05.01 after that without any problem.

@stweil then backported a couple of commits to tesseract 3.05.01 branch to fix the problem regarding lept_free() and I rebuilt leptonica with the latest source and then built tesseract 3.05.01. It built without the lept_free error.

It is possible that I did not build leptonica using the script which does autobuild and configure, but rather just did
```
git pull origin
make
sudo make install
```
I also built tesseract 4.0 from master branch after that. I noticed in both of these, that leptonica version was reported as 1.74.2.

After following Amit and Stefan's suggestions to see whether I had multiple versions of files causing the older version to display, I decided to rebuild leptonica again. This time I did `make distclean` in leptonica directory before running the build script.

Then without needing to rebuild tesseract, `tesseract -v` showed that it was using leptonica 1.74.4. 

@amitdo So, as mentioned by Stefan, it is not necessary to rebuild tesseract to use the newer leptonica library.

**Comment by DanBloomberg** [comment]
@shreeshrii

Thanks!  Very nice summary.

We have several ways to build tesseract and the associated libraries.
An embarrassment of riches, as the French would say (except
in their own way).

It seems to me that the current suggestions in the leptonica
README.html for building with autotools are still valid.
It also references the documentation in
     https://github.com/tesseract-ocr/tesseract/wiki/Compiling
and I see that you updated that page 2 weeks ago.  Would
you make any further changes there?

**Comment by Shreeshrii** [comment]
he wiki pages are public and have been updated by different people at different times.  I did update the Compiling wiki page with the needed leptonica version recently. 

There are multiple Install/Compiling instructions.
I think that https://github.com/tesseract-ocr/tesseract/blob/master/INSTALL.GIT.md is better. 

I will try to streamline the compiling page - maybe delete duplicated info and refer to the installation page instead. However, it will require review by @stweil @egorpugin and @zdenop .

**Comment by DanBloomberg** [comment]
Actually, the page I referred to looked pretty good, and I was just
referring to the small section on constraints for compiling leptonica.

**Comment by vb216** [comment]
I seem to be hitting the problem too - trying to add in a cross compile for powerpc into our travis build setup, building leptonica first and then tesseract and I seem to be hitting this same issue no matter what I try, if I use 3.0.5.01 download. If I pull latest straight from git, it compiles fine. Also builds fine for android, mac, windows, probably even native ppc. 

@Shreeshrii you mention some backports to 3.0.5.1, could you help with any details on those? I looked through the commit log but from a quick look from around Jun I didn't spot anything immediately obvious. I'm wondering if its something I can apply as a patch, just that pulling a non-release version usually ends up with headaches down the road

**Comment by amitdo** [comment]
>git clone -q --branch=3.05 https://github.com/tesseract-ocr/tesseract.git tesseract-3.05

This will fetch https://github.com/tesseract-ocr/tesseract/tree/3.05, but the latest 3.05.x is 3.05.1: https://github.com/tesseract-ocr/tesseract/tree/3.05.01

Currently, version 4.0 still has the legacy engine from 3.0x (plus the new LSTM engine).
It can be used with the 3.05/3.04 traineddata files (--oem 0 or --oem 3).
