### ISSUE TITLE
API/ABI changes review for Tesseract

### ISSUE THREAD

**Issue by lvc** [tesseract-ocr/tesseract#793]
The review of API/ABI changes for Tesseract since 3.00 version: https://abi-laboratory.pro/tracker/timeline/tesseract/

Hope it will be helpful for users and maintainers of the library.

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

The tool checks _all_ API symbols declared in header files (doesn't take docs into account), so there may be some false positives.

Thank you.

![tesseract-1](https://cloud.githubusercontent.com/assets/1517837/24391131/5b074572-139e-11e7-89c2-d98ca1e67dc2.png)

![tesseract-2](https://cloud.githubusercontent.com/assets/1517837/24391366/b84779ea-139f-11e7-804e-f6ec094b4225.png)

## Environment
* Linux x86_64
* GCC 4.9
* Tesseract 3.00 and higher

**Comment by zdenop** [comment]
Why you put this on in the issue tracker?

**Comment by lvc** [comment]
To take attention of library developers on the results first.

Thank you.

**Comment by Shreeshrii** [comment]
@lvc Thanks! I have added info to the documentation wiki at

https://github.com/tesseract-ocr/tesseract/wiki/Documentation

**Comment by amitdo** [comment]
@lvc,
Thanks for the info.

3.01 and 3.01 are missing from the report. 

The bottom line is that we break the ABI in almost every release.

**Comment by amitdo** [comment]
@lvc,
FYI, since 3.02 there is an "--enable-visibility" option for the configure script.

**Comment by zdenop** [comment]
@lvc : Thanks, but there is place for this: [tesseract developer forum.](https://groups.google.com/forum/#!forum/tesseract-dev)
@amitdo : Broken ABI is know issue ;-) Even API is not stable. See dev forum.

**Comment by lvc** [comment]
@amitdo,

> 3.01 and 3.03 are missing from the report

Added 3.01 and 3.03 versions to the report: https://abi-laboratory.pro/tracker/timeline/tesseract/

Thank you.

![tesseract-4](https://cloud.githubusercontent.com/assets/1517837/24453656/d431e726-1499-11e7-9f4c-c6fed0aff533.png)

**Comment by Shreeshrii** [comment]
@lvc If possible, instead of current version, add 'master' and '3.05' branch. Thanks!

**Comment by lvc** [comment]
@Shreeshrii,

Done: https://abi-laboratory.pro/tracker/timeline/tesseract/

Please let me know when it should be switched to 3.06 or 4.0.

![tesseract-5](https://cloud.githubusercontent.com/assets/1517837/25801811/724dac08-3400-11e7-9af3-ff379784aeaf.png)

**Comment by Shreeshrii** [comment]
Thanks.

Actually, 3.05 and master 4.0 are going to be two parralel tracks for a
while.

Zdenko is going to tag 3.05.01 release soon, so that should be compared
with 3.05.0 for changes. Any changes after that on 3.05 branch should
follow as current in that sequence.

Similarly, 4.0.0alpha may be followed by a beta or release, plus changes in
master branch.

If not possible to do in same table, you can make a separate one for 4.0.

Thanks.

**Comment by Shreeshrii** [comment]
@lvc  Please update this for the master branch now, as 4.0.0-beta.1 has been released.

Thanks!

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/tesseract/

Thanks for notifying!

![tesseract-6](https://user-images.githubusercontent.com/1517837/38016610-3517fe98-3278-11e8-8060-0c3a4905cb11.png)

**Comment by Shreeshrii** [comment]
@lvc Thank you for your prompt response.

Will tracker keep getting updated automatically as more commits are made to master branch?

**Comment by lvc** [comment]
@Shreeshrii Yes, it's updated every Mon, Wed and Fri.

**Comment by Shreeshrii** [comment]
Thanks, that's great.

**Comment by amitdo** [comment]
@lvc, 
Please add 4.0.0.

**Comment by amitdo** [comment]
@lvc,
You removed the beta but didn't add the final 4.0.0.

See also above comment from @zdenop.

**Comment by zdenop** [comment]
@amitdo : see https://github.com/tesseract-ocr/tesseract/issues/793#issuecomment-377124796 I expect it will be generated automatically today.

**Comment by lvc** [comment]
> @lvc: thanks for prompt replay. Something like
> `https://abi-laboratory.pro/?view=timeline&l=tesseract&graph.svg?v=1.1` is not possible?
> It would be much more easier to integrate online image to wiki (without need to render it locally) and it would allow automatic update of image after update of analyze.
> 
> Or is there another way how to integrate your tool to github project (somehing like lgtm or coverity - see [Readme.md](https://github.com/tesseract-ocr/tesseract/blob/master/README.md))?

Good idea!

I'll implement it ASAP as part of the abi-tracker project. Thank you!

**Comment by lvc** [comment]
> @lvc,
> You removed the beta but didn't add the final 4.0.0.
> 
> See also above comment from @zdenop.

Report is updated: https://abi-laboratory.pro/?view=timeline&l=tesseract

Got this image by CutyCapt:

![tesseract](https://user-images.githubusercontent.com/1517837/47791510-ed09af80-dd2a-11e8-8e29-9272a2a34751.png)

**Comment by Shreeshrii** [comment]
My suggestion is to link the image with the html version so that the links
to changelog etc work.
Thanks.

**Comment by zdenop** [comment]
@lvc : table is stored in wiki repository so I need to update it manually; graph is linked directly to your page, but it seem github is caching it: https://camo.githubusercontent.com/ae5fd8a19e16ec27b191716fe3079ecd35ad07d3/68747470733a2f2f6162692d6c61626f7261746f72792e70726f2f747261636b65722f67726170682f7465737365726163742f67726170682e7376673f763d312e31

**Comment by Shreeshrii** [comment]
@lvc Please update the report for https://github.com/tesseract-ocr/tesseract/tree/4.1

4.1 is planned as a bug-fix release. Master is 5.0 alpha. 

It will be good to check status of API compatibility for 4.1.

See related discussion at https://github.com/tesseract-ocr/tesseract/issues/2249#issuecomment-482787146

**Comment by linuxhw** [comment]
@Shreeshrii 

> It will be good to check status of API compatibility for 4.1.

Done.

See https://abi-laboratory.pro/?view=timeline&l=tesseract

**Comment by stweil** [comment]
@linuxhw, most important is currently the API compatibility from 4.0 to 4.1. Can this be checked, too?

**Comment by linuxhw** [comment]
> @linuxhw, most important is currently the API compatibility from 4.0 to 4.1. Can this be checked, too?

The report is currently for 4.0 vs git 4.1 branch (instead of master).

**Comment by Shreeshrii** [comment]
@linuxhw Thank you!

Current Status

Git(4.1) | 2019-04-3021:43 | 4 | changelog | 99% | 35 new | 0
-- | -- | -- | -- | -- | -- | --

**Comment by zdenop** [comment]
> Yes, it's updated every Mon, Wed and Fri.
@linuxhw @lvc : Is this still valid?

**Comment by linuxhw** [comment]
> > Yes, it's updated every Mon, Wed and Fri.
> > @linuxhw @lvc : Is this still valid?

Temporarily not. I'm working currently on restoring the service after the storage failure (since Apr 4). The report for Tesseract was updated manually 4 days ago.

Update it again?

**Comment by zdenop** [comment]
Please update it on Monday - I want to test some commits today evening (European time ;-) )

**Comment by zdenop** [comment]
Thanks. You start update now.

**Comment by linuxhw** [comment]
Report is updated.

**Comment by zdenop** [comment]
@linuxhw: can you please updare reportfor 4.1? Hopefully we created the last rc (3) for 4.1

**Comment by stweil** [comment]
@zdenop, please remember to update the `VERSION` file when tagging a release.

**Comment by lvc** [comment]
> @linuxhw: can you please updare reportfor 4.1? Hopefully we created the last rc (3) for 4.1

Failed to build latest master due to error:

```
libtool: link: ( cd ".libs" && rm -f "libtesseract.la" && ln -s "../libtesseract.la" "libtesseract.la" )
/bin/sh ../../libtool  --tag=CXX   --mode=link g++  -g -Og -w -fpermissive -fPIC -std=c++14  -L/home/andrey/ABI_Tracker/installed/leptonica/1.74.1/lib -o tesseract tesseract-tesseractmain.o libtesseract.la -L/home/andrey/ABI_Tracker/installed/leptonica/1.74.1/lib -llept  -fopenmp  -larchive   -lrt -lpthread 
libtool: link: g++ -g -Og -w -fpermissive -fPIC -std=c++14 -o .libs/tesseract tesseract-tesseractmain.o -fopenmp  -L/home/andrey/ABI_Tracker/installed/leptonica/1.74.1/lib ./.libs/libtesseract.so -llept -larchive -lrt -lpthread -fopenmp -Wl,-rpath -Wl,/home/andrey/ABI_Tracker/installed/tesseract/current/lib
./.libs/libtesseract.so: undefined reference to `signal_exit(int)'
```

**Comment by zdenop** [comment]
Can you provide details about environment you use and how did you build tesseract?

**Comment by lvc** [comment]
> Can you provide details about environment you use and how did you build tesseract?

`./configure --enable-shared --prefix="..." CFLAGS="-g -Og -w -fpermissive -fPIC" CXXFLAGS="-g -Og -w -fpermissive -fPIC" PKG_CONFIG_PATH=/.../leptonica/1.74.1/lib/pkgconfig LIBLEPT_HEADERSDIR=/.../leptonica/1.74.1/include/ LDFLAGS='-L/.../leptonica/1.74.1/lib' CFLAGS='-g -Og -I/.../leptonica/1.74.1/include'`
`make`

Fedora 21, x86_64, GCC 4.9.2 20150212 (Red Hat 4.9.2-6).

The environment is not changed since the last successful build.

**Comment by stweil** [comment]
The linker error was introduced by commit 78ced35a8b0a5b4c400f0d2088601e7f2e2500cb. I fixed it in commit 9a5f72479a3189ab467d64a12c670e5040946261, so I think this issue can be closed.

**Comment by lvc** [comment]
> The linker error was introduced by commit [78ced35](https://github.com/tesseract-ocr/tesseract/commit/78ced35a8b0a5b4c400f0d2088601e7f2e2500cb). I fixed it in commit [9a5f724](https://github.com/tesseract-ocr/tesseract/commit/9a5f72479a3189ab467d64a12c670e5040946261).

Report is updated: https://abi-laboratory.pro/index.php?view=timeline&l=tesseract (no changes since previous update of the report).

![Tesseract-6](https://user-images.githubusercontent.com/1517837/59608279-b0ee5800-911d-11e9-85a7-2464b4f0dc98.png)

**Comment by zdenop** [comment]
@lvc : 4.1.1 was just released... Can you please update https://abi-laboratory.pro/?view=timeline&l=tesseract and remove 4.1.1-rc2 from that comparison?

**Comment by linuxhw** [comment]
> @lvc : 4.1.1 was just released... Can you please update https://abi-laboratory.pro/?view=timeline&l=tesseract and remove 4.1.1-rc2 from that comparison?

Done. Thanks.

**Comment by zdenop** [comment]
thanks!

**Comment by zdenop** [comment]
Hm.. when I run it localy on my linux machine I had 100% backward compatibility...

**Comment by linuxhw** [comment]
> Hm.. when I run it localy on my linux machine I had 100% backward compatibility...

Please attach your ABI dumps here for both versions for debugging.

**Comment by zdenop** [comment]
I can provide after 1st of January...

**Comment by zdenop** [comment]
see https://github.com/lvc/abi-dumper/issues/23

**Comment by Shreeshrii** [comment]
@linuxhw please update the tracker for the latest version from main branch. Also a heads-up for upcoming 5.0.0 release.

**Comment by Shreeshrii** [comment]
@lvc Tesseract 5.0 has been released. please update https://abi-laboratory.pro/?view=timeline&l=tesseract 

Thanks!

**Comment by linuxhw** [comment]
> @lvc Tesseract 5.0 has been released. please update https://abi-laboratory.pro/?view=timeline&l=tesseract
> 
> Thanks!

Done

**Comment by linuxhw** [comment]
> @lvc Tesseract 5.0 has been released. please update https://abi-laboratory.pro/?view=timeline&l=tesseract
> 
> Thanks!

![Tesseract-0](https://user-images.githubusercontent.com/15686469/150002690-882ee468-bfe4-4526-bf49-10325e5c29dc.png)
