### ISSUE TITLE
Error while use in external binding

### ISSUE THREAD

**Issue by Vakhrushev** [tesseract-ocr/tesseract#1652]
binding https://github.com/GeertJohan/go.tesseract

### Environment

* **Tesseract Version**: 
tesseract 4.0.0-beta.1-342-ge7c1
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0
 Found AVX
 Found SSE

* **Platform**: 
Linux aisvls 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux

### Current Behavior:
/usr/include/tesseract/capi.h:108:15: error: expected declaration specifiers or '...' before '*' token
 typedef bool (*TessCancelFunc)(void* cancel_this, int words
               ^
/usr/include/tesseract/capi.h:109:15: error: expected declaration specifiers or '...' before '*' token
 typedef bool (*TessProgressFunc)(ETEXT_DESC* ths, int left,
               ^
/usr/include/tesseract/capi.h:404:72: error: unknown type name 'TessCancelFunc'
 TESS_API void TESS_CALL TessMonitorSetCancelFunc( ETEXT_DES
                                                            
/usr/include/tesseract/capi.h:407:74: error: unknown type name 'TessProgressFunc'
 TESS_API void TESS_CALL TessMonitorSetProgressFunc( ETEXT_D

### Suggested Fix:

**Comment by stweil** [comment]
Thank you for reporting this. It is indeed a regression which was introduced by commit 87d33b6c9.

**Comment by stweil** [comment]
Until this is fixed, you can add `#include <bool.h>` before including `capi.h` (or add that statement there).

**Comment by stweil** [comment]
Pull request #1654 fixes this issue.
